CREATE DATABASE mydb4;
USE mydb4;

CREATE TABLE Customers
SELECT * FROM w3schools.Customers;

DESC Customers;

ALTER TABLE Customers
MODIFY COLUMN CustomerID INT PRIMARY KEY AUTO_INCREMENT;

DESC Employees;

CREATE TABLE Employees
SELECT * FROM w3schools.Employees;

ALTER TABLE Employees
MODIFY COLUMN EmployeeID INT PRIMARY KEY AUTO_INCREMENT;